### ISSUE TITLE
So many mistakes, and this for a paid for learning resource

### ISSUE THREAD

**Issue by Duncro** [PacktPublishing/Python-Machine-Learning-By-Example-Third-Edition#2]
Chapter 2:
Directory names (and structure) miss match, ratings have decimals in them, so reading in as integers fail
The code in book (on PackPub.com) differs from this code.....?! Even the file obtained from the book is different, containing CSV files not DAT

I see chapter 1 code isn't in here but that's also a mess in the actual book on Packt, requiring frequent edits to get stuff working, which I have found in another book as well.

Very disappointed in the couple of books I've looked into so far, quite a sub par paid for service (Packt)

**Comment by orlandombaa** [comment]
Hi @Duncro  
di you unpacked the data correctly?

**Comment by haydenliu** [comment]
@Duncro I am sorry you encountered the issue. However, at the time the book was writen, the data files were in DAT format, but later updated to CSV format. The book authors have no control of when and how the data will be updated. Fortunately, you can simply change the separator from :: to , and you should be able to read the input data without issues. Not sure what you mean by "reading in as integers fail", as there is this line of code "rating = int(rating)" that converts it to integer.

We will update the CSV format in the next edition, and please don't hesitate to let us know if there is anything else needs updates
