### ISSUE TITLE
Chapter 2 with mistakes: Building a movie recommender with Naïve Bayes

### ISSUE THREAD

**Issue by orlandombaa** [PacktPublishing/Python-Machine-Learning-By-Example-Third-Edition#4]

**Comment by orlandombaa** [comment]
The example of movie recommender doesnt work. It seems that it is related with the type of variable.

**Comment by haydenliu** [comment]
Per https://files.grouplens.org/datasets/movielens/ml-latest-small-README.html , it now only has 610 users and 9742 movies. Readers can update this two lines accordingly: 

n_users = 6040
n_movies = 3706

Also the data files are now updated to CSV format. Readers can simply change the separator from :: to , and you should be able to read the input data without issues.
